### ISSUE TITLE
Nginx config file manual edits get lost upon doing CLI changes

### ISSUE THREAD

**Issue by tka85** [evgeniy-khist/letsencrypt-docker-compose#39]
I realized that any manual edits of Nginx's config files are lost whenever I run `docker compose run --rm cli` to add/remove domains or force certificate refresh.

Not sure if there is a workaround for this.

Btw, your project is excellent! Kudos on a very well-thought out and practical execution of a common problem.

**Comment by evgeniy-khist** [comment]
Yes, this is the expected behaviour. I will mention it the section about advanced Nginx configuration. The workaround is to edit the `nginx.conf` Handlebars template https://github.com/evgeniy-khist/letsencrypt-docker-compose/blob/main/templates/nginx.conf.hbs

Thanks for sharing your findings. The feedback from users helps to improve the project.
